org: alonsobenitess2
service: awsimplementation-reportes

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::458879724766:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_reportes

functions:
  crear:
    handler: user/CrearReporte.lambda_handler
    events:
      - http:
          path: /reporte/crear
          method: post
          cors: true
          integration: lambda
    environment:
      CONNECTIONS_TABLE: Connections
      INCIDENTS_TABLE: Incidents

  listar:
    handler: admin/ListarReportes.lambda_handler
    events:
      - http:
          path: /reporte/listar
          method: get
          cors: true
          integration: lambda

  obtener:
    handler: admin/ObtenerReporte.lambda_handler
    events:
      - http:
          path: /reporte/{uuid}
          method: get
          cors: true
          integration: lambda

  eliminar:
    handler: admin/EliminarReporte.lambda_handler
    events:
      - http:
          path: /reporte/{uuid} 
          method: delete
          cors: true
          integration: lambda

  # WebSocket Lambda Functions (sin eventos - los configurar√°s manualmente en API Gateway)
  connect:
    handler: connect.lambda_handler
    environment:
      CONNECTIONS_TABLE: Connections
      INCIDENTS_TABLE: Incidents

  disconnect:
    handler: disconnect.lambda_handler
    environment:
      CONNECTIONS_TABLE: Connections

  default:
    handler: default.lambda_handler
    environment:
      CONNECTIONS_TABLE: Connections
      INCIDENTS_TABLE: Incidents

resources:
  Resources:

    #########################################
    # DynamoDB Tables
    #########################################
    ReportesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    IncidentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Incidents
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
